// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwRKc8VURb8AZNDox99Grv0_LWgvzLNM',
    appId: '1:133589739101:web:60514849199574e2728fb4',
    messagingSenderId: '133589739101',
    projectId: 'reclaim-2ca54',
    authDomain: 'reclaim-2ca54.firebaseapp.com',
    storageBucket: 'reclaim-2ca54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9G60zjF398IN_rKXPumrXpqOfLPKExL4',
    appId: '1:133589739101:android:e74b7df55ab73cd0728fb4',
    messagingSenderId: '133589739101',
    projectId: 'reclaim-2ca54',
    storageBucket: 'reclaim-2ca54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJxs-QNt75w0gzm1SYHyCoHv_FAtY7gFQ',
    appId: '1:133589739101:ios:26b0219a5eae6d30728fb4',
    messagingSenderId: '133589739101',
    projectId: 'reclaim-2ca54',
    storageBucket: 'reclaim-2ca54.firebasestorage.app',
    iosBundleId: 'com.sandalishela.reclaim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJxs-QNt75w0gzm1SYHyCoHv_FAtY7gFQ',
    appId: '1:133589739101:ios:26b0219a5eae6d30728fb4',
    messagingSenderId: '133589739101',
    projectId: 'reclaim-2ca54',
    storageBucket: 'reclaim-2ca54.firebasestorage.app',
    iosBundleId: 'com.sandalishela.reclaim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwRKc8VURb8AZNDox99Grv0_LWgvzLNM',
    appId: '1:133589739101:web:561e7186cc415dcc728fb4',
    messagingSenderId: '133589739101',
    projectId: 'reclaim-2ca54',
    authDomain: 'reclaim-2ca54.firebaseapp.com',
    storageBucket: 'reclaim-2ca54.firebasestorage.app',
  );
}
